-- 1. Total revenue generated by each restaurant
-- Useful for comparing performance between restaurants
SELECT R.Name AS Restaurant_Name,
       SUM(O.Amount) AS Total_Revenue
FROM Orders O
JOIN Restaurant R ON O.Restaurant_ID = R.Restaurant_ID
GROUP BY R.Name;

-- 2. Average order value per restaurant
-- Helps management understand customer spending behavior
SELECT R.Name AS Restaurant_Name,
       AVG(O.Amount) AS Average_Order_Value
FROM Orders O
JOIN Restaurant R ON O.Restaurant_ID = R.Restaurant_ID
GROUP BY R.Name;

-- 3. Number of orders placed by each customer
-- Identifies loyal or frequent customers
SELECT C.Name AS Customer_Name,
       COUNT(O.O_ID) AS Total_Orders
FROM Customer C
LEFT JOIN Orders O ON C.C_ID = O.C_ID
GROUP BY C.Name;

-- 4. Customers who have placed more than 1 order
-- Useful for loyalty programs
SELECT C.Name AS Customer_Name,
       COUNT(O.O_ID) AS Order_Count
FROM Customer C
JOIN Orders O ON C.C_ID = O.C_ID
GROUP BY C.Name
HAVING COUNT(O.O_ID) > 1;

-- 5. Monthly total revenue
-- Helps track sales trends over time
SELECT
    EXTRACT(YEAR FROM O.Order_Date) AS Order_Year,
    EXTRACT(MONTH FROM O.Order_Date) AS Order_Month,
    SUM(O.Amount) AS Monthly_Revenue
FROM Orders O
GROUP BY
    EXTRACT(YEAR FROM O.Order_Date),
    EXTRACT(MONTH FROM O.Order_Date)
ORDER BY Order_Year, Order_Month;


-- 6. Highest single order amount per restaurant
-- Identifies big-spending orders
SELECT R.Name AS Restaurant_Name,
       MAX(O.Amount) AS Highest_Order
FROM Orders O
JOIN Restaurant R ON O.Restaurant_ID = R.Restaurant_ID
GROUP BY R.Name;

-- 7. Lowest order amount per restaurant
-- Helps analyze pricing strategy and minimum spending
SELECT R.Name AS Restaurant_Name,
       MIN(O.Amount) AS Lowest_Order
FROM Orders O
JOIN Restaurant R ON O.Restaurant_ID = R.Restaurant_ID
GROUP BY R.Name;

-- 8. Total salary expense per restaurant
-- Used for financial planning and cost control
SELECT R.Name AS Restaurant_Name,
       SUM(W.Salary) AS Total_Salary_Cost
FROM Waiter W
JOIN Restaurant R ON W.Restaurant_ID = R.Restaurant_ID
GROUP BY R.Name;

-- 9. Average salary of waiters per shift
-- Helps evaluate wage distribution between shifts
SELECT Shift,
       AVG(Salary) AS Average_Salary
FROM Waiter
GROUP BY Shift;

-- 10. Number of reservations made per restaurant
-- Measures customer demand and popularity
SELECT R.Name AS Restaurant_Name,
       COUNT(Res.Reservation_ID) AS Total_Reservations
FROM Reservation Res
JOIN Restaurant R ON Res.Restaurant_ID = R.Restaurant_ID
GROUP BY R.Name;

-- 11. Customers who made reservations but never placed an order
-- Useful for marketing follow-ups
SELECT C.Name AS Customer_Name
FROM Customer C
JOIN Reservation R ON C.C_ID = R.C_ID
WHERE C.C_ID NOT IN (
    SELECT DISTINCT O.C_ID FROM Orders O
);

-- 12. Total number of delivered orders
-- Helps evaluate delivery service usage
SELECT COUNT(*) AS Delivered_Orders
FROM Delivery;

-- 13. Orders that were delivered with their total amounts
-- Useful for delivery performance tracking
SELECT O.O_ID,
       O.Amount,
       D.Delivery_Date
FROM Orders O
JOIN Delivery D ON O.O_ID = D.O_ID;

-- 14. Menu items priced above the average menu price
-- Helps identify premium items
SELECT Meal_Name, Price
FROM Menu
WHERE Price > (SELECT AVG(Price) FROM Menu);

-- 15. Total discount value offered by each restaurant
-- Useful for evaluating marketing and promotions cost
SELECT R.Name AS Restaurant_Name,
       SUM(Ofr.Discount) AS Total_Discount_Offered
FROM Offers Ofr
JOIN Restaurant R ON Ofr.Restaurant_ID = R.Restaurant_ID
GROUP BY R.Name;



